### ISSUE TITLE
Newer Version of Python

### ISSUE THREAD

**Issue by runninbear5** [lisaong/stackup-workshops#47]
@lisaong I have been trying to get pytorch running on a raspberry pi for days now and this is the first, mostly simple, tutorial I have found that actually works. However, for the project I am working on, it requires a python version 3.6 or higher. Is there anyway I can upgrade the python installed on your image or is there a simple way to remake the files to use python 3.6 or higher instead of 3.5?

**Comment by lisaong** [comment]
hi @runninbear5, the docker image is defined here: https://github.com/lisaong/stackup-workshops/blob/master/pi-pytorch/docker/Dockerfile

You can change it to build python 3.6 from source instead of using the built-in python distribution from stretch (py3.5).

https://gist.github.com/dschep/24aa61672a2092246eaca2824400d37f

However, it isn't clear whether there is a distribution of PyTorch for Raspberry Pi for Python 3.6.

**Comment by runninbear5** [comment]
Thank you for explaining how to change it to python 3.6.

When you used python 3.5, how did you get the build for the raspberry pi. I noticed you were using a package called torch-raspi. I had found this package but didn't know if there was a way to update that as well. Would you have any idea how to upgrade this package or who made it and how to contact them?

Thanks for the help.

**Comment by lisaong** [comment]
Hi, torch-raspi is made by a developer: https://pypi.org/project/torch-raspi/0.4.0/. There are no other releases as far as I can tell.

Once you've updated to python 3.6 or 3.7. you can try the steps below to build torch on the Raspberry Pi:
https://gist.github.com/wngr/d7de37e31551362223be39c80641c1b4

**Comment by lisaong** [comment]
Hi, closing the issue as someone has posted a whl for Pytorch on Python 3.7 Raspberry Pi: https://discuss.pytorch.org/t/pytorch-1-3-wheels-for-raspberry-pi-python-3-7/58580

I'll see if I can make a docker image with the latest version, but in the meantime you can always manually pip install from your 3.7 environment on the Raspberry Pi. Good luck!
